Repository ReachFive/identity-android-sdk, pull requests merged in 2019-07, with the labels that each got.

#3 Implement signup/login with a phone number and profile update
  README.md
  app/build.gradle
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/LoginRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SignupRequest.kt
Labels: feature, require_review

#4 Implement request password reset
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestPasswordResetRequest.kt
Labels: feature

#5 Implement verify phone number
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/VerifyPhoneNumberRequest.kt
Labels: feature, require_review

#6 Implement update email
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/LoginProviderRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/LoginRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestModels.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestPasswordResetRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/VerifyPhoneNumberRequest.kt
Labels: feature

#7 Implement update phone number
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestModels.kt
Labels: feature

#8 Create env variables to set the ReachFive domain & client ID
  .gitignore
  app/build.gradle
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
Labels: fix, require_review

#12 Update the documentation
  CHANGELOG.md
  README.md
  RELEASE.md
Labels: enhancement

#13 Don't ignore the test `testSuccessfulSignupWithLocalPhoneNumber`
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
Labels: fix

#14 Implement password update
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/UpdatePasswordRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Callback.kt
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
Labels: feature

#15 Rename the `UpdatePasswordRequest` data classes
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/UpdatePasswordRequest.kt
Labels: fix

#16 Implement logout
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
Labels: feature

#17 Release v4.1.0
  CHANGELOG.md
  build.gradle
Labels: release

#18 Complete the release workflow & update the library badge
  README.md
  RELEASE.md
Labels: fix

#19 Parcelize all the SDK core models
  app/build.gradle
  build.gradle
  sdk-core/build.gradle
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Address.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProviderConfig.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestModels.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SdkConfig.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SdkInfos.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/UpdatePasswordRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/User.kt
  sdk-facebook/build.gradle
  sdk-google/build.gradle
  sdk-webview/build.gradle
Labels: enhancement

#21 Translate French comments in English
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/User.kt
Labels: fix

#20 Rename the `open_id` scope into `openid`
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
Labels: fix, require_review

#22 Implement the authentication flow with code in the WebViewProvider
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthCodeRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
Labels: feature

#23 Call the authorization code flow with PKCE
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthCodeRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Pkce.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
Labels: feature

#24 Release v4.2.0
  CHANGELOG.md
  build.gradle
Labels: release

#26 Improve test fixtures
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
Labels: fix

#27 Add an HTTP logger for debug mode
  sdk-core/build.gradle
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
Labels: feature

#25 Change default scope behaviour
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ClientConfigResponse.kt
Labels: feature

#28 Annoying chore: Reformat codebase
  .circleci/config.yml
  app/src/androidTest/java/com/reach5/identity/sdk/demo/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  app/src/main/res/drawable/ic_power_settings.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/menu/menu.xml
  app/src/test/java/com/reach5/identity/sdk/demo/ExampleUnitTest.kt
  build.gradle
  sdk-core/src/main/AndroidManifest.xml
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/Provider.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestModels.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/UpdatePasswordRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Pkce.kt
  sdk-facebook/build.gradle
  sdk-facebook/src/main/AndroidManifest.xml
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/AndroidManifest.xml
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/AndroidManifest.xml
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/res/layout/reachfive_login_activity.xml
Labels: chore

#29 Improve test launch
  app/build.gradle
  app/src/androidTest/java/com/reach5/identity/sdk/demo/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/test/java/com/reach5/identity/sdk/demo/ExampleUnitTest.kt
Labels: chore

#30 Refactor and enrich models
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Consent.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProfileAddress.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/RequestModels.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/AuthCodeRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/LoginProviderRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/LoginRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/RequestPasswordResetRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/SignupRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdateEmailRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePasswordRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePhoneNumberRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/VerifyPhoneNumberRequest.kt
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
Labels: enhancement, refactoring

#32 Don't pass the `accessToken` in the `requestPasswordReset` method
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
Labels: fix

#33 Implement get profile
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
Labels: feature

#31 Use AndroidX instead of android.support
  README.md
  app/build.gradle
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  app/src/main/res/layout/toolbar.xml
  gradle.properties
  sdk-core/build.gradle
  sdk-google/build.gradle
  sdk-webview/build.gradle
Labels: enhancement

#34 IdToken is now optional
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/OpenIdUser.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProviderConfig.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
Labels: enhancement, require review

#35 Merge `logout` and `logoutWithProviders`
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Labels: fix

#36 Add a test for get profile with missing scope
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
Labels: enhancement
