Repository ReachFive/identity-android-sdk, pull requests merged in 2019-08, with the labels that each got.

#37 Release v5.0.0
  CHANGELOG.md
  build.gradle
Labels: release

#40 Delete the `authToken` argument from the `updatePassword`
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePasswordRequest.kt
Labels: fix, require review

#41 Release v5.0.1
  CHANGELOG.md
  build.gradle
Labels: release

#42 Fix the signup of the sandbox
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt
Labels: fix

#38 Upgrade Android Kotlin version and Gradle wrapper
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
Labels: dependency upgrade

#45 Delete the `code` parameter from `AuthToken` and `AuthTokenResponse`
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthTokenResponse.kt
Labels: fix

#44 Delete the `redirectUrl` argument from the `logout` method
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Labels: fix

#47 Change the type of `consentType`
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Consent.kt
Labels: fix

#49 Release v5.1.0
  CHANGELOG.md
  build.gradle
Labels: release

#52 Refresh Token minor improvements
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Labels: chore

#54 Release v5.2.0
  CHANGELOG.md
  build.gradle
Labels: release

#55 Improve the ReachFiveError model
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
Labels: feature

#56 Release v5.3.0
  CHANGELOG.md
  build.gradle
Labels: release

#59 Fix the profile address model
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProfileAddress.kt
Labels: fix

#60 Release v5.3.1
  CHANGELOG.md
  build.gradle
Labels: release

#65 Remove the `signedUid` attribute from the profile
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
Labels: fix

#57 Improve tests
  app/build.gradle
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
Labels: chore, fix

#66 Remove no provider found error
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Labels: fix, require review

#67 Release v5.3.2
  CHANGELOG.md
  build.gradle
Labels: release
