Repository ReachFive/identity-android-sdk, pull requests merged in 2019-09, with the labels that each got.

#71 Add passwordless
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/PasswordlessAuthType.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessAuthorizationCodeRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessCodeVerificationRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessStartRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Callback.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Pkce.kt
Labels: feature

#79 Return the custom fields when the profile is fetched
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Labels: fix

#80 Release v5.4.2
  CHANGELOG.md
  build.gradle
Labels: release

#81 Add missing fields in the get profile request
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
Labels: fix

#82 Release v5.4.3
  CHANGELOG.md
  build.gradle
Labels: release
