Repository ReachFive/identity-android-sdk, pull requests merged in 2020-11, with the labels that each got.

#110 update icon app
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: enhancement

#111 Release v6.0.0
  CHANGELOG.md
  build.gradle
Labels: release

#112 Update the changelog of 6.0.0
  CHANGELOG.md
Labels: bug

#114 Don't specify the ReachFive origin domain in the README
  README.md
Labels: bug

#113 fix webView user-agent
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
Labels: bug

#115 Change the launch mode of the `RedirectionActivity` activity
  sdk-core/src/main/AndroidManifest.xml
Labels: bug

#116 Release v6.0.1
  CHANGELOG.md
  build.gradle
Labels: release

#117 Add the redirectURL parameter in the signup method
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/SignupRequest.kt
Labels: enhancement
