Repository ReachFive/identity-android-sdk, pull requests merged in 2020-06, with the labels that each got.

#90 Configure scheme with client ID
  .gitignore
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SdkConfig.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
Labels: feature

#91 Release v5.5.0
  CHANGELOG.md
  build.gradle
Labels: release

#92 Add the `scope`parameter to the `loginWithProvider` method
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/Provider.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
Labels: enhancement

#94 Release v5.6.0
  CHANGELOG.md
  build.gradle
Labels: release

#93 Add error_message_key in error bodies
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
Labels: feature
