Repository ReachFive/identity-android-sdk, pull requests merged in 2021-09, with the labels that each got.

#128 [CA-349] Update du SDK Facebook
  app/build.gradle
  sdk-facebook/build.gradle
Labels: dependency upgrade

#130 Release v6.2.0
  CHANGELOG.md
  build.gradle
Labels: release

#131 Publish to Sonatype
  .circleci/config.yml
  app/.gitignore
  app/build.gradle
  app/debug.keystore
  app/keystore.jks
  app/proguard-rules.pro
  app/src/androidTest/java/com/reach5/identity/sdk/demo/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/reach5/identity/sdk/demo/AuthenticatedActivity.kt
  app/src/main/java/com/reach5/identity/sdk/demo/DevicesAdapter.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  app/src/main/java/com/reach5/identity/sdk/demo/ProvidersAdapter.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_power_settings.xml
  app/src/main/res/layout/activity_authenticated.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/callback_login.xml
  app/src/main/res/layout/device_item.xml
  app/src/main/res/layout/provider_item.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/layout/webauthn_devices.xml
  app/src/main/res/layout/webauthn_login.xml
  app/src/main/res/layout/webauthn_signup.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/web/.firebaserc
  app/web/.gitignore
  app/web/firebase.json
  app/web/public/.well-known/assetlinks.json
  bintray.gradle
  build.gradle
  sdk-core/build.gradle
  sdk-facebook/build.gradle
  sdk-google/build.gradle
  sdk-webview/build.gradle
  settings.gradle
Labels: require review, release, dependency upgrade

#132 Release v6.2.1
  CHANGELOG.md
Labels: release

#133 Sonatype migration Pt.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: refactoring

#136 Upgrade Kotlin
  build.gradle
  sdk-core/build.gradle
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFiveWebAuthn.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApiCallback.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthToken.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Consent.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/OpenIdUser.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProfileAddress.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ProviderConfig.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/ReachFiveError.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/SdkConfig.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/AuthCodeRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/LoginProviderRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/LoginRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessStartRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessVerificationRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/ProfileSignupRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/RefreshRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/RequestPasswordResetRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/SignupRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdateEmailRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePasswordRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePhoneNumberRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/VerifyPhoneNumberRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/AuthenticationPublicKeyCredential.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/RegistrationPublicKeyCredential.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebAuthnLoginRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebAuthnRegistrationRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/webAuthn/WebauthnSignupCredential.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/AuthenticationToken.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/ClientConfigResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/PasswordlessVerificationResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/TokenEndpointResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/AuthenticationOptions.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/DeviceCredential.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/R5PublicKeyCredentialDescriptor.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/webAuthn/RegistrationOptions.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/Jwt.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/PkceAuthCodeFlow.kt
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/build.gradle
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
  sdk-webview/build.gradle
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
Labels: require review, refactoring, dependency upgrade

#135 Sonatype migration: CI
  .circleci/config.yml
  build.gradle
Labels: require review

#140 Missed renaming folders
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/Provider.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFiveWebAuthn.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/RedirectionActivity.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/api/ReachFiveApiCallback.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/AuthToken.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/Consent.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/OpenIdUser.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/Profile.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/ProfileAddress.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/ProviderConfig.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/ReachFiveError.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/SdkConfig.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/SdkInfos.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/AuthCodeRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/LoginProviderRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/LoginRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/PasswordlessStartRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/PasswordlessVerificationRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/ProfileSignupRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/RefreshRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/RequestPasswordResetRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/SignupRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/UpdateEmailRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/UpdatePasswordRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/UpdatePhoneNumberRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/VerifyPhoneNumberRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/webAuthn/AuthenticationPublicKeyCredential.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/webAuthn/RegistrationPublicKeyCredential.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/webAuthn/WebAuthnLoginRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/webAuthn/WebAuthnRegistrationRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/webAuthn/WebauthnSignupCredential.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/AuthenticationToken.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/ClientConfigResponse.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/PasswordlessVerificationResponse.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/TokenEndpointResponse.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/webAuthn/AuthenticationOptions.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/webAuthn/DeviceCredential.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/webAuthn/R5PublicKeyCredentialDescriptor.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/webAuthn/RegistrationOptions.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/Callback.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/Jwt.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/PkceAuthCodeFlow.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/Scope.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/WebAuthn.kt
  sdk-facebook/src/main/java/co/reachfive/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/co/reachfive/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/WebViewProviderConfig.kt
Labels: chore
