Repository ReachFive/identity-android-sdk, pull requests merged in 2021-05, with the labels that each got.

#125 Refactor passwordless verification API calls
  CHANGELOG.md
  app/src/main/java/com/reach5/identity/sdk/demo/AuthenticatedActivity.kt
  app/src/main/java/com/reach5/identity/sdk/demo/JavaMainActivity.java
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/Provider.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApi.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/api/ReachFiveApiCallback.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/AuthToken.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/PasswordlessAuthType.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessAuthorizationCodeRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessCodeVerificationRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessStartRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/PasswordlessVerificationRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/requests/UpdatePasswordRequest.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/AuthenticationToken.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/PasswordlessVerificationResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/models/responses/TokenEndpointResponse.kt
  sdk-core/src/main/java/com/reach5/identity/sdk/core/utils/PkceAuthCodeFlow.kt
  sdk-facebook/src/main/java/com/reach5/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/com/reach5/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/com/reach5/identity/sdk/webview/WebViewProviderConfig.kt
Labels: refactoring, require review

#120 Add ProGuard rules for network model classes
  sdk-core/build.gradle
  sdk-core/proguard-rules.pro
Labels: question

#124 Fix/signup with password
  app/src/main/java/com/reach5/identity/sdk/demo/MainActivity.kt
  sdk-core/build.gradle
  sdk-core/proguard-rules.pro
Labels: fix
