Repository ReachFive/identity-android-sdk, pull requests merged in 2022-07, with the labels that each got.

#154 Make `Address` fields nullable
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/OpenIdUser.kt
Labels: fix

#157 Release v7.0.3
  CHANGELOG.md
  libversion.gradle
Labels: release

#155 [1] [CA-1508] Use Custom Tabs in SLO flows
  build.gradle
  libversion.gradle
  sdk-core/build.gradle
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/RedirectionActivity.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/OpenIdUser.kt
  sdk-webview/build.gradle
  sdk-webview/src/main/AndroidManifest.xml
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/ReachFiveLoginActivity.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/WebViewProvider.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/WebViewProviderConfig.kt
  sdk-webview/src/main/res/layout/reachfive_login_activity.xml
Labels: enhancement

#158 [2] [CA-1489] Login through custom tab
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/RedirectionActivity.kt
Labels: feature

#159 [3] Breakdown client
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/OAuthClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordlessClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ProfileClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFiveWebAuthn.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/SocialLoginClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/WebauthnClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/AuthToken.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/requests/PasswordlessVerificationRequest.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/models/responses/webAuthn/RegistrationOptions.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/Jwt.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/PkceAuthCodeFlow.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/utils/WebAuthn.kt
  sdk-facebook/src/main/java/co/reachfive/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/co/reachfive/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/WebViewProvider.kt
Labels: refactoring

#161 [5] Revise client construction & Activity handling
  libversion.gradle
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ActivityResultHandler.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/JavaReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/OAuthClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/PasswordlessClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/Provider.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/ReachFive.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/SocialLoginClient.kt
  sdk-core/src/main/java/co/reachfive/identity/sdk/core/WebauthnClient.kt
  sdk-facebook/src/main/java/co/reachfive/identity/sdk/facebook/FacebookProvider.kt
  sdk-google/src/main/java/co/reachfive/identity/sdk/google/GoogleProvider.kt
  sdk-webview/src/main/java/co/reachfive/identity/sdk/webview/WebViewProvider.kt
Labels: refactoring
